import './globals.css'
import { Roboto } from 'next/font/google'
import {NextUI as NextUIProvider} from "./_providers/NextUI";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["400", "500", "700", "900"],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextUIProvider>
          <main className='light'>
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  )
}
